export const STATUS_LABELS = {
  not_submitted: 'Not Submitted',
  submitted: 'Submitted',
  under_review: 'Under Review',
  graded: 'Graded',
  returned_for_revision: 'Returned',
  rejected: 'Rejected',
  active: 'Active',
  due_soon: 'Due Soon',
  expired: 'Expired',
  archived: 'Archived',
  draft: 'Draft',
  completed: 'Completed',
  approved: 'Approved',
  missing: 'Missing',
};

export const STATUS_EDGE_COLORS = {
  not_submitted: 'bg-danger',
  submitted: 'bg-brass',
  under_review: 'bg-brass',
  graded: 'bg-info',
  returned_for_revision: 'bg-brass',
  rejected: 'bg-danger',
  active: 'bg-success',
  due_soon: 'bg-brass',
  expired: 'bg-danger',
  archived: 'bg-muted',
  draft: 'bg-muted',
  completed: 'bg-success',
  approved: 'bg-success',
  missing: 'bg-danger',
};

export const BADGE_CLASSES = {
  not_submitted: 'bg-danger/10 text-danger',
  submitted: 'bg-brass/10 text-brass',
  under_review: 'bg-brass/10 text-brass',
  graded: 'bg-info/10 text-info',
  returned_for_revision: 'bg-brass/10 text-brass',
  rejected: 'bg-danger/10 text-danger',
  active: 'bg-success/10 text-success',
  due_soon: 'bg-brass/10 text-brass',
  expired: 'bg-danger/10 text-danger',
  archived: 'bg-muted/10 text-muted',
  draft: 'bg-muted/10 text-muted',
  completed: 'bg-success/10 text-success',
  approved: 'bg-success/10 text-success',
  missing: 'bg-danger/10 text-danger',
};
